version: '3.8'

volumes:
  db_data:  # Este volume é utilizado para persistir os dados do banco de dados PostgreSQL

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data  # Corrigido o caminho para o diretório correto do PostgreSQL
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_DB: ${POSTGRES_DB}    

  app:  
    build: ./
    volumes:
      - ./app:/app 
    ports:
      - "8080:80" 
    depends_on:
      - db  