version: '3.8'

volumes:
  db_data:
  cached:

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data # Corrigido o caminho para o diretório correto do PostgreSQL
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  cached:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cached:/data

  app:
    build: ./
    volumes:
      - ./app:/app

    ports:
      - '8080:80'
    depends_on:
      - db
