version: '3.8'

volumes:
  db_data:
  cached:

services:
  tecnospeed-db:
    image: postgres:latest
    container_name: postgres-server
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - tecnospeed-networks

  tecnospeed-cached:
    image: redis:6.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cached:/data
    networks:
      - tecnospeed-networks

  app:
    build: ./
    restart: always
    volumes:
      - .:/src
      - /src/node_modules

    ports:
      - '8000:8000'
    depends_on:
      - tecnospeed-db
      - tecnospeed-cached
    networks:
      - tecnospeed-networks

networks:
  tecnospeed-networks:
    driver: bridge
