{
 "title": "dashboard_tecno",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status Servidor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eventloop(S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_metric{instance=\"localhost:8000\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{instance=\"localhost:8000\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (http_requests_total{job=\"app\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}