global:
  scrape_interval:     15s 

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - 'localhost:9090'

  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9000'
    
  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'docker:9323'
    